
apiVersion: v1
kind: Service
metadata:
  name: attendance-api-service
  labels:
    app: attendance-api
spec:
  type: LoadBalancer
  selector:
    app: attendance-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
